### PR TITLE
Converting to Flask

### PR DESCRIPTION
**Pull request by catherinedevlin**
Not ready yet!

### CODE REVIEW

**Comment by migurski** [comment]
Looks cool, but sounds like it's not ready and also in a different language from ours.

**Comment by monfresh** [comment]
I think @catherinedevlin keeps meaning to send her PRs to [18F/codetalker](https://github.com/18F/codetalker), but is sending them here instead.

**Comment by catherinedevlin** [comment]
Ugh, my apologies.  Thanks @monfresh for catching that.

The sad thing is that a couple days ago I noticed that the PR was defaulting to come back here instead of to 18F/codetalker:master and changed its destination.  But today I started a new one and forgot.  Wish I knew how to change the default PR destination instead of relying on my feeble memory.

**Comment by louh** [comment]
Thanks @monfresh and @catherinedevlin for clarifying, it all makes sense now :-)

To @catherinedevlin, when you have a chance, do you mind sharing more with us about the Codetalker project? Will it be primarily NAICS or many other classifications? Is this supplementing or replacing the NAICS information currently hosted by the US Census? 

As the original creator of the NAICS API I am actually really happy this is getting picked up by 18F and would love to follow/support what you are doing!

**Comment by monfresh** [comment]
@catherinedevlin AFAIK, GitHub does not provide the ability to set a default destination for PRs from a fork. The default destination is always set to the parent repository (the one that was forked originally).

**Comment by dwcaraway** [comment]
> To @catherinedevlin, when you have a chance, do you mind sharing more with us about the  Codetalker project? Will it be primarily NAICS or many other classifications? Is this supplementing or replacing the NAICS information currently hosted by the US Census?

Hi all, Codetalker was originally a port of NAICS api to Api.data.gov, but is becoming a catch-all utility API for procurement-related codes and information. 18F uses NAICs and other codes for advanced filtering on our procurement products like [FBOpen](https://fbopen.gsa.gov/). You can see the upcoming features on [our main github issue repo](https://github.com/18F/afsmallbiz/labels/Product:%20Codetalker).

I originally set Codetalker as a NAICS api fork as I thought we might push features upstream. However, I think we're bound to deviate quite a bit from the original design so upstream pushes might not make sense, especially given the recent node.js -> python conversion.

I didn't realize that the pull requests would default back to this upstream. We can recreate the repo without a fork but keep the original attribution if that would work better.

**Pull request closed without merging**
